# Generated by Django 5.2.1 on 2025-05-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
